stages:
  - api

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

generate-typescript-models:
  stage: api
  image: docker.io/hdmstuttgartquizzit/asyncapi-generator:0.1.0
  script:
    - echo "Generating Source Code from API specifications"
    - cd api/generate/typescript
    - npm run generate
    - npm publish
  rules:
    - when: manual
      allow_failure: true
