stages:
  - api-generate
  - api-publish

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  NPM_CACHE_DIR: $CI_PROJECT_DIR/.npm/

# Cache modules for this project
cache:
  key: $CI_PROJECT_ID
  paths:
    - $NPM_CACHE_DIR

generate-typescript-models:
  stage: api-generate
  image: node:19.8.1
  script:
    - echo "Generating Source Code from API specifications"
    - cd spec/generate/typescript
    - npm install --cache $NPM_CACHE_DIR
    - npm run generate
  artifacts:
    expire_in: 30 min
    paths:
      - spec/generate/typescript/

publish-models:
  stage: api-publish
  image: node:19.8.1
  dependencies:
    - generate-typescript-models
  script:
    - echo "Attempting to publish Typescript Models"
    - cd spec/generate/typescript
    - npm publish
  rules:
    - when: manual
      allow_failure: true

