stages:
  - api-generate
  - api-publish

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

# Cache modules for this project
cache:
  key: $CI_PROJECT_ID
  paths:
    - .npm/

generate-typescript-models:
  stage: api-generate
  image: node:19.8.1
  script:
    - echo "Generating Source Code from API specifications"
    - cd spec/generate/typescript
    - npm install --cache .npm
    - npm run generate
  artifacts:
    expire_in: 30 min
    paths:
      - spec/generate/typescript/

publish-models:
  stage: api-publish
  image: node:19.8.1
  dependencies:
    - generate-typescript-models
  script:
    - echo "Attempting to publish Typescript Models"
    - cd spec/generate/typescript
    - npm publish
  rules:
    - when: manual
      allow_failure: true

