# http:
#   port: 8880
# log:
#   level: info
#   file-level: info
# hybrid-die:
#   disabled: yes
#   search:
#     timeout: 10s
# game:
#   scored-points-to-win: 3
#   questions: "./questions.json"
