version: "3.8"

services:
  generate-typescript:
    build:
      context: generate/typescript
      dockerfile: Dockerfile
    entrypoint: npm
    command: "run ci"
    working_dir: /src/generate/typescript
    volumes:
      - "./generate/typescript/package.json:/src/generate/typescript/package.json"
      - "./generate/typescript/.npmrc:/src/generate/typescript/.npmrc"
      - "./websocket-asyncapi.yaml:/src/websocket-asyncapi.yaml"
      - "./swagger.yaml:/src/swagger.yaml"
    environment:
      NPM_TOKEN: "${GITLAB_TOKEN}"
    restart: "no"
