swagger: "2.0"
info:
  description: |-
    Shared Components of Quizzit REST API specification.
    
    Some useful links:
    - [Quizzit repository](https://im-gitlab.hdm-stuttgart.de/quizzit)
  contact:
    email: "H3rby7@users.noreply.github.com"
  license:
    name: Unlicensed
  version: 0.1.0
components:
  schemas:
    Icon:
      title: Icon
      description: Reference to an icon
      type: string
    Id:
      title: Identifier
      description: A unique ID
      type: string
    UserInterfaceScale:
      description: Key-Value Entry for preferences
      type: object
      properties:
        userInterfaceScale:
          title: User Interface Scale
          description: Interface Scaling factor in %.
          type: number
      required:
        - userInterfaceScale
    VoiceOutput:
      description: Key-Value Entry for preferences
      type: object
      properties:
        voiceOutput:
          title: Voice Output
          description: Enable Voice Output / Screen Reading
          type: boolean
      required:
        - voiceOutput
    Photosensitive:
      description: Key-Value Entry for preferences
      type: object
      properties:
        photosensitive:
          title: Photosensitive
          description: Whether or not the player is photosensitive.
          type: boolean
      required:
        - photosensitive
    VirtualDie:
      description: Key-Value Entry for preferences
      type: object
      properties:
        virtualDie:
          title: Virtual Die
          description: Enable using the virtual die instead of a physical one.
          type: boolean
      required:
        - virtualDie
    Preferences:
      title: Preferences
      description: List any set preferences.
      type: array
      minItems: 0
      anyOf:
        - $ref: "#/components/schemas/UserInterfaceScale"
        - $ref: "#/components/schemas/VoiceOutput"
        - $ref: "#/components/schemas/Photosensitive"
        - $ref: "#/components/schemas/VirtualDie"
    Profile:
      title: Profile
      description: Configuration of one person including preferences.
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        name:
          type: string
        icon:
          $ref: "#/components/schemas/Icon"
        preferences:
          $ref: "#/components/schemas/Preferences"
      required:
        - id
        - name
        - preferences
    Category:
      title: Category
      description: A category for questions and panels.
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        name:
          title: Name
          description: Name of the category to be used in the game
          type: string
        icon:
          $ref: "#/components/schemas/Icon"
      required:
        - id
        - name
        - icon
    Answer:
      title: Answer
      description: One possible answer to a question.
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        text:
          title: Text
          description: The actual answer text to be displayed to the player during the game.
          type: string
        choiceId:
          $ref: "#/components/schemas/Id"
        disabled:
          title: Disabled
          description: Disable this answer possibility. For example due to a joker usage.
          type: boolean
      required:
        - id
        - text
    Question:
      title: Question
      description: Represents a question inside the game
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        category:
          $ref: "#/components/schemas/Category"
        query:
          type: string
        answers:
          title: Possible answers
          description: The possible, not necessarily correct, answers.
          type: array
          minItems: 2
          items:
            $ref: "#/components/schemas/Answer"
      required:
        - id
        - category
        - query
        - answers
