openapi: 3.0.3
info:
  title: Quizzit - OpenAPI 3.0
  description: |-
    This is the first draft of the Quizzit REST API specification.
    We also provide a Websocket interface for certain information, refer to the asyncapi.yml for these definitions.
    
    Some useful links:
    - [Quizzit repository](https://im-gitlab.hdm-stuttgart.de/quizzit)
  contact:
    email: "H3rby7@users.noreply.github.com"
  license:
    name: Unlicensed
  version: 0.1.0
servers:
  - url: localhost
    description: Local development
paths:
  /health:
    get:
      summary: Alive?
      description: Health Endpoint
      responses:
        '200':
          description: is healthy
        '500':
          description: something is off
