openapi: 3.1.0
info:
  title: Quizzit REST
  description: |-
    Quizzit REST API specification.
    We also provide a Websocket interface for certain information, refer to the asyncapi.yml for these definitions.
    
    Some useful links:
    - [Quizzit repository](https://gitlab.mi.hdm-stuttgart.de/quizzit)
  contact:
    name: "H3rby7"
    email: "H3rby7@users.noreply.github.com"
    url: "https://github.com/h3rby7"
  license:
    name: MIT
    identifier: https://choosealicense.com/licenses/mit/
  version: 0.3.0
servers:
  - url: http://localhost:8080
    description: Local development
  - url: http://quizzit.local
    description: RaspberryPi in local network
paths:
  /health:
    get:
      tags:
        - system
      summary: Health Endpoint
      description: Is the service up and running?
      responses:
        '200':
          description: is healthy
        '500':
          description: something is off
  /settings:
    get:
      tags:
        - settings
      summary: Retrieve Settings
      description: Get the current settings
      responses:
        '200':
          description: Successfully retrieved settings
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/UserSettings'
    patch:
      tags:
        - settings
      summary: Update Settings
      description: Update Settings with new values
      requestBody:
        $ref: '#/components/requestBodies/UserSettings'
      responses:
        '200':
          description: 'patch applied'
  /game/stop:
    post:
      tags:
        - game
      summary: Stop Quizzit
      description: Reset all points, questions and go back to Welcome Screen
      responses:
        '200':
          description: Successfully stopped the game

components:
  schemas:
    Game:
      description: Game Settings
      type: object
      properties:
        scoredPointsToWin:
          description: How many points a player needs to win the game, values below '1' are ignored.
          type: integer
          default: -1
        questions:
          description: Filepath to the questions catalog to use, leave empty to make no change
          type: string
          default: ""
    Enabled:
      description: Is Enabled, leave empty to make no change
      type: string
      default: ""
      enum: 
       - ""
       - "ENABLED"
       - "DISABLED"
    HybridDie:
      description: Hybrid-Die Settings
      type: object
      properties:
        enabled:
          $ref: "#/components/schemas/Enabled"
        search:
          description: Settings related to searching a hybrid-die
          type: object
          properties:
            timeout:
              description: Timeout as GOLANG duration string, leave empty to make no change
              type: string
              default: ""
    UserSettings:
      description: UserSettings
      type: object
      properties:
        game:
          $ref: '#/components/schemas/Game'
        hybridDie:
          $ref: '#/components/schemas/HybridDie'
  requestBodies:
    UserSettings:
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/UserSettings'
