openapi: 3.0.3
info:
  title: Quizzit REST
  description: |-
    Quizzit REST API specification.
    We also provide a Websocket interface for certain information, refer to the asyncapi.yml for these definitions.
    
    Some useful links:
    - [Quizzit repository](https://gitlab.mi.hdm-stuttgart.de/quizzit)
  contact:
    name: "H3rby7"
    email: "H3rby7@users.noreply.github.com"
    url: "https://github.com/h3rby7"
  license:
    name: Unlicensed
  version: 0.2.0
servers:
  - url: http://localhost:8080
    description: Local development
paths:
  /health:
    get:
      tags:
        - system
      summary: Health Endpoint
      description: Is the service up and running?
      responses:
        '200':
          description: is healthy
        '500':
          description: something is off
  /settings:
    get:
      tags:
        - settings
      summary: Retrieve Settings
      description: Get the current settings
      responses:
        '200':
          $ref: '#/components/schemas/Settings'
    patch:
      tags:
        - settings
      summary: Update Settings
      description: Update Settings with new values
      requestBody:
        $ref: '#/components/requestBodies/Settings'
      responses:
        '200':
          description: 'patch applied'

components:
  requestBodies:
    Settings:
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/Settings'
  schemas:
    Game:
      description: Game Settings
      type: object
      properties:
        pointsToWin:
          type: integer
    Settings:
      description: Quizzit Settings
      type: object
      properties:
        game:
          $ref: '#/components/schemas/Game'
