openapi: 3.0.3
info:
  title: Quizzit - OpenAPI 3.0
  description: |-
    This is the first draft of the Quizzit REST API specification.
    We also provide a Websocket interface for certain information, refer to the asyncapi.yml for these definitions.
    
    Some useful links:
    - [Quizzit repository](https://gitlab.mi.hdm-stuttgart.de/quizzit)
  contact:
    email: "H3rby7@users.noreply.github.com"
  license:
    name: Unlicensed
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: Local development
paths:
  /health:
    get:
      tags:
        - system
      summary: Health Endpoint
      description: Is the service up and running?
      responses:
        '200':
          description: is healthy
        '500':
          description: something is off
  /settings:
    get:
      tags:
        - settings
      summary: Retrieve Settings
      description: Get the current settings
      responses:
        '200':
          $ref: '#/components/schemas/Settings'
    post:
      tags:
        - settings
      summary: Post Settings
      description: Set current config to new values
      requestBody:
        $ref: '#/components/requestBodies/Settings'
      responses:
        '200':
          description: 'patch applied'

components:
  requestBodies:
    Settings:
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/Settings'
  schemas:
    Game:
      description: Game Settings
      type: object
      properties:
        pointsToWin:
          type: integer
    Settings:
      description: Quizzit Settings
      type: object
      properties:
        game:
          $ref: '#/components/schemas/Game'
